if(!settings.multipleView) settings.batchView=false;
settings.tex="xelatex";
defaultfilename="Fact5-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

import olympiad;
import cse5;
pointpen = black;
pathpen = black;
pathfontpen = black;
anglepen = black;
anglefontpen = black;
pointfontsize = 10;
defaultpen(fontsize(10pt));
size(8cm); // set a reasonable default
usepackage("amsmath");
usepackage("amssymb");
settings.tex="latex";
settings.outformat="pdf";

pair A = dir(110);
pair B = dir(210);
pair C = dir(330);
pair I = incenter(A, B, C);
draw(A--B--C--cycle);
draw(unitcircle);
pair L = dir(270);
pair I_A = 2*L-I;
draw(CP(L, I), blue);

draw(A--I_A, dotted);

dot("$A$", A, dir(A));
dot("$B$", B, dir(190));
dot("$C$", C, dir(-10));
dot("$I$", I, dir(60));
dot("$L$", L, dir(225));
dot("$I_A$", I_A, dir(I_A));

/* Source generated by TSQ */
